name: root
description: "Workspace root"

environment:
  sdk: ">=3.9.2 <4.0.0"
  flutter: ">=3.35.3 <4.0.0"

dev_dependencies:
  sizzle_lints: ^2.1.7

workspace:
  - app
  # Core
  - core/common
  - core/logger
  - core/rest_client
  - core/ui_library
  - core/filesystem_storage
  - core/llm_client
  - core/session_scheduler
  # Feature
  - feature/settings
  - feature/home
  - feature/global_experts
  - feature/rooms
