name: rooms
description: Rooms feature for Whiteboard Planner
version: 0.1.0
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.9.2 <4.0.0"
  flutter: ">=3.35.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  filesystem_storage:
    path: ../../core/filesystem_storage
  flutter_bloc: ^9.1.1
  meta: ^1.12.0
  uuid: ^4.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  bloc_test: ^10.0.0

flutter:
